import Java.util.Scanner;
class  Example3
{
publi Static void main(String ags[])
{
    Double u1,u2,u3,bill
    
    Scanner s=new Scanner (System. in)
    
    System.out.println("Enter unit values is");
    Double.s.nextInt
    u1=200*34.50;
    u2=300*34.50;
    u3=400*34.50;
    
    totel bill=ul=u1+u2+u3
    gst=(totel*18)/100
    
    System.out.println("Enter the Totel Bill is:"+totel bill);
    System.out.println("Enter the gst is:"+gst);
}
}