//WAP to accept project marks, internal marks, external marks. find total marks.

/*:
1. 70% on project
2. 20% on external
3. 10% on internal*/

impot java.util Scanner;
class  Example2

{
public Static void main(String args [])
{
    Scanner int=Scanner (System.in);
    
    int  pr=0,et=0,it=0,int
    
    
    System.out.println("Enter The pr,et,it Value is :");
    int= nextLnt();
    pr=(pr/100)*70;
    et=(et/100)*20;
    it=(it/100)*10;
    totel mars =pr+et+it
    System.out.println("The Totel Marks is:"+totel marks);
}
    
}